#include "msg.h"

extern const char usage_longstr[] = "---------------------UDT tool help---------------------\n"
						   "Usage: sendfile [-p][server_port] [options]\n"
						   "       ------------------------------------\n"
                           "       receivefile [-s][server_ip] [-p][server_port] [-r][remote_path_file]\n"
						   "       [-l][local_path_file] [options]\n"
						   "       -------------------------------------------------------------------\n"
                           "       sendfile/receivefile [-h|--help]\n"
						   "       --------------------------------\n\n"
                           "Available commands:\n"
                           "  -p, --server_port    #         server port to listen on/connect to\n"
						   "  -s, --server_ip      #         server ip listen on/connect to\n"
                           "  -m, --MTU            #         Maximum Transfer Unit\n"    
                           "  -e, --UDT_RCVBUF     #         UDT receiving buffer size\n"
                           "  -w, --window_size    #         Flight flag size (window size)\n"
						   "  -f, --UDP_SNDBUF     #         UDP sending buffer size\n"
						   "  -t, --UDP_RCVBUF     #         UDP receiving buffer size\n"
						   "  -y, --UDT_MAXMSG     #         Maximum datagram message size\n"
						   "  -o, --UDT_SNDBUF     #         Maximum buffer in sending queue\n"
						   "  -b, --UDT_MAXBW      #         Maximum bandwidth (bytes per second) that the connection can use\n"
						   "  -u, --UDT_SNDDATA    #         Size of data in the sending buffer\n"
						   "  -i, --UDT_RCVDATA    #         Size of data available for recv\n"
						   "  -l, --local_file     #         local path file name\n"
						   "  -r  --remote_file    #         remote path file name\n"
						   "  -k  --UDP_CC                   set custom congestion control algorithm\n" 
						   "  -d  --SOCK_DGRAM               set SOCK_DGRAM socktype. Defult is SOCK_STREAM\n"
						   "  -h, --help                     print this message and quit\n";	